/**
 * lib/og.tsx — shared Open Graph image renderer. Every route's opengraph-image.tsx
 * calls `renderOg({ title, subtitle?, eyebrow? })`. Runs in the Node runtime (needed
 * to read font files with `fs`) and is compatible with `output: 'export'` because it
 * is evaluated at build time only, never at request time.
 *
 * ADR-0005 "Liquid Glass" §7: light forms + wordmark + title, no gradient text and
 * no dark panel — mirrors the static /public/og-fallback.png generated by
 * scripts/generate-placeholders.mjs so every OG card reads as the same calm family.
 * One typeface (Manrope, ADR-0005 §3) — satori cannot parse WOFF2, so the .woff copy
 * is read directly.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ImageResponse } from "next/og";

export const ogSize = { width: 1200, height: 630 };
export const ogContentType = "image/png";

const uiFontRegular = readFileSync(join(process.cwd(), "app/fonts/manrope-latin-400-normal.woff"));
const uiFontBold = readFileSync(join(process.cwd(), "app/fonts/manrope-latin-600-normal.woff"));

const INK = "#0F1A1A";
const TEAL = "#0F766E";
const GREY = "#5B5F68";

/** Wraps a title into lines of roughly `max` characters, capped at 3 lines. */
function wrapTitle(title: string, max = 30): string[] {
  const words = title.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
    if (lines.length === 3) break;
  }
  if (current && lines.length < 3) lines.push(current);

  return lines.slice(0, 3);
}

export function renderOg(o: { title: string; subtitle?: string; eyebrow?: string }): ImageResponse {
  const lines = wrapTitle(o.title);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          flexDirection: "column",
          justifyContent: "space-between",
          backgroundColor: "#F6F8F9",
          backgroundImage:
            "radial-gradient(circle at 8% 8%, rgba(15,118,110,0.16) 0%, rgba(15,118,110,0) 45%), " +
            "radial-gradient(circle at 96% 18%, rgba(94,234,212,0.20) 0%, rgba(94,234,212,0) 42%), " +
            "radial-gradient(circle at 30% 108%, rgba(255,255,255,0.9) 0%, rgba(255,255,255,0) 46%)",
          fontFamily: "Manrope",
          padding: "72px 76px",
        }}
      >
        {o.eyebrow && (
          <div
            style={{
              display: "flex",
              fontSize: 22,
              fontWeight: 700,
              letterSpacing: 3,
              textTransform: "uppercase",
              color: TEAL,
            }}
          >
            {o.eyebrow}
          </div>
        )}

        <div style={{ display: "flex", flexDirection: "column" }}>
          {lines.map((line) => (
            <div
              key={line}
              style={{
                display: "flex",
                fontSize: 64,
                fontWeight: 600,
                lineHeight: 1.05,
                letterSpacing: -2,
                color: INK,
              }}
            >
              {line}
            </div>
          ))}
          {o.subtitle && (
            <div style={{ display: "flex", marginTop: 22, fontSize: 26, color: GREY }}>{o.subtitle}</div>
          )}
        </div>

        <div style={{ display: "flex", alignItems: "center", justifyContent: "space-between" }}>
          <div style={{ display: "flex", fontSize: 28, fontWeight: 600, color: INK }}>RA Machine</div>
          <div style={{ display: "flex", fontSize: 18, color: GREY }}>
            ramachine.com · Kolkata, India · Exporting worldwide
          </div>
        </div>
      </div>
    ),
    {
      ...ogSize,
      fonts: [
        { name: "Manrope", data: uiFontRegular, weight: 400, style: "normal" },
        { name: "Manrope", data: uiFontBold, weight: 600, style: "normal" },
      ],
    },
  );
}
