/**
 * lib/og.tsx — shared Open Graph image renderer. Every route's opengraph-image.tsx
 * calls `renderOg({ title, subtitle?, eyebrow? })`. Runs in the Node runtime (needed to
 * read font files with `fs`) and is compatible with `output: 'export'` because it is
 * evaluated at build time only, never at request time.
 *
 * ADR-0002 visual refresh: a spark rule, the title/eyebrow on a white left panel, and a
 * dark ink→steel right panel carrying a small laser-head icon mark — mirrors the static
 * /public/og-fallback.png generated by scripts/generate-placeholders.mjs so every OG
 * card (dynamic per-page, or the static fallback) reads as the same family.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";
import { ImageResponse } from "next/og";

export const ogSize = { width: 1200, height: 630 };
export const ogContentType = "image/png";

const uiFont = readFileSync(join(process.cwd(), "app/fonts/manrope-latin-600-normal.woff"));
const displayFont = readFileSync(
  join(process.cwd(), "app/fonts/barlow-semi-condensed-latin-600-normal.woff"),
);

const INK = "#111214";
const STEEL = "#1F4E79";
const SPARK = "#F26A21";
const PANEL_WIDTH = 360;

/** Wraps a title into lines of roughly `max` characters, capped at 3 lines. */
function wrapTitle(title: string, max = 34): string[] {
  const words = title.split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    const next = current ? `${current} ${word}` : word;
    if (next.length > max && current) {
      lines.push(current);
      current = word;
    } else {
      current = next;
    }
    if (lines.length === 3) break;
  }
  if (current && lines.length < 3) lines.push(current);

  return lines.slice(0, 3);
}

export function renderOg(o: { title: string; subtitle?: string; eyebrow?: string }): ImageResponse {
  const lines = wrapTitle(o.title);

  return new ImageResponse(
    (
      <div
        style={{
          width: "100%",
          height: "100%",
          display: "flex",
          backgroundColor: "#ffffff",
          fontFamily: "Manrope",
        }}
      >
        <div
          style={{
            flex: 1,
            display: "flex",
            flexDirection: "column",
            justifyContent: "space-between",
            padding: "72px 64px",
          }}
        >
          <div style={{ width: 56, height: 4, backgroundColor: SPARK, display: "flex" }} />

          <div style={{ display: "flex", flexDirection: "column" }}>
            {o.eyebrow && (
              <div
                style={{
                  fontSize: 22,
                  fontWeight: 600,
                  letterSpacing: 2,
                  textTransform: "uppercase",
                  color: SPARK,
                  marginBottom: 20,
                  display: "flex",
                }}
              >
                {o.eyebrow}
              </div>
            )}
            <div style={{ display: "flex", flexDirection: "column" }}>
              {lines.map((line) => (
                <div
                  key={line}
                  style={{
                    fontFamily: "Barlow Semi Condensed",
                    fontSize: 62,
                    lineHeight: 1.05,
                    color: INK,
                    display: "flex",
                  }}
                >
                  {line}
                </div>
              ))}
            </div>
            {o.subtitle && (
              <div style={{ marginTop: 24, fontSize: 26, color: "#5B5F68", display: "flex" }}>
                {o.subtitle}
              </div>
            )}
          </div>

          <div style={{ fontSize: 20, color: "#7A7E87", display: "flex" }}>
            ramachine.com · Kolkata, India · Exporting worldwide
          </div>
        </div>

        <div
          style={{
            width: PANEL_WIDTH,
            height: "100%",
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            backgroundColor: INK,
            backgroundImage: `linear-gradient(160deg, ${STEEL} 0%, ${INK} 65%)`,
          }}
        >
          {/* Laser-head icon mark: gantry beam, head, dashed cutting beam — echoes the
              site's Laser icon and the illustration style used across /public. */}
          <div style={{ display: "flex", flexDirection: "column", alignItems: "center" }}>
            <div style={{ width: 170, height: 26, borderRadius: 10, backgroundColor: STEEL, display: "flex" }} />
            <div
              style={{
                marginTop: 8,
                width: 72,
                height: 52,
                borderRadius: 10,
                backgroundColor: "#ffffff",
                display: "flex",
              }}
            />
            <div style={{ marginTop: 14, width: 5, height: 90, backgroundColor: SPARK, display: "flex" }} />
          </div>
        </div>
      </div>
    ),
    {
      ...ogSize,
      fonts: [
        { name: "Manrope", data: uiFont, weight: 600, style: "normal" },
        { name: "Barlow Semi Condensed", data: displayFont, weight: 600, style: "normal" },
      ],
    },
  );
}
